// Variables that describe what you want to do

export const IS_LOCATION_PERMISSION_GRANTED = 'IS_LOCATION_PERMISSION_GRANTED'
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_ROUTE_DISTANCE_METERS = 'SET_ROUTE_DISTANCE_METERS';
export const SET_RANDOM_POLYGON_COORDINATES = 'SET_RANDOM_POLYGON_COORDINATES';